### ISSUE TITLE
Calibração

### ISSUE THREAD

**Issue by 3ldr0n** [3ldr0n/Automatiza-o-7ghz#3]
## Preparar o código para a calibração.

Escrever as funções que serão usadas futuramente para fazer a calibração.

- [x] Criar as funções para pegar a posição do telescópio em azimute e altitude
- [x] Definir o delta para a posição no céu que dever ser apontada [WIP]
- [x] Apontar para o céu, se baseando no azimute e na altitude

**Comment by AmauriKudaka** [comment]
Edson,

O script com calibração funcionou bem, sábado e domingo.

Hoje vou manobrar o load manualmente.

Abraços

Em sex, 7 de dez de 2018 às 16:48, Edison Neto <notifications@github.com>
escreveu:
